apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.3.0
  name: kube-state-metrics
  namespace: monitoring
spec:
  clusterIP: None
  externalIPs: []
  ports:
    - name: https-main
      port: 8443
    - name: https-self
      port: 9443
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-prometheus
  type: ClusterIP
